### ISSUE TITLE
Maybe we can talk through here?

### ISSUE THREAD

**Issue by EricLStevens** [EricLStevens/LikeHatchetButWithMagic#1]
Seems pretty reasonable.

**Comment by EricLStevens** [comment]
@4cite

**Comment by 4cite** [comment]
Alright, lets start an outline of what we want from the early game. Afterwards we will worry about the storyline and the chronological events. I'd do it now but its too late at night. I'll update tomorrow.

**Comment by EricLStevens** [comment]
Sounds good. Busy day today, but I'll get to working on what I'd like the mechanics to look like.

**Comment by 4cite** [comment]
I updated the wiki. Just learning github but left all my work there.
